version: '3.8'

services:
  db:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USERNAME: ${DB_USERNAME}
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
      # Left in case I want to populate.
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  # In case I don't have access to dbeaver or the like
  pgadmin:
    image: dpage/pgadmin4
    ports:
      # Worst Port I could think of to bind
      - 5150:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - db
    networks:
      # Use database as hostname to connect to postgres.
      - postgres-network
    volumes:
      # Don't forget to sudo chown -R 5050:5050 ./pgadmin-data
      # or else it will fail to bind
      - ./pgadmin-data/:/var/lib/pgadmin/
  redis:
    image: redis:7.0-alpine
    ports:
      - 6379:6379
    command:
      redis-server --save 20 1 --loglevel warning
      # --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data/redis

volumes:
  cache:
    driver: local

networks:
  postgres-network:
    driver: bridge
